# Generated by Django 3.2.3 on 2021-06-01 04:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genre_dict',
            field=models.JSONField(default=accounts.models.genre_default),
        ),
    ]
