# Generated by Django 3.2.3 on 2021-05-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
